config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'games#index'
  resources :games do
    resources :pieces
    put '/make_move' => 'games#make_move'
    
    patch 'castle_kingside', to: 'games#castle_kingside', as: :castle_kingside
    patch 'castle_queenside', to: 'games#castle_queenside', as: :castle_queenside
  end
  
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_board.html.erb
<script>
    $(function (){
        $('.draggable').draggable({
            snap: '.droppable',
            snapMode: "outer",
            snapTolerance: 40,
            containment: 'table',
            drag: function( event, ui ){
                window.piece_id = event.target.attributes[1].value
            }
        });
        $( '.droppable' ).droppable({
            drop: function( event, ui ) {

            }
        });
        $( '.droppable' ).on( "drop", function( event, ui ) {
            var x = event.currentTarget.attributes[1].value
            var y = event.currentTarget.attributes[2].value
            var game_id = event.currentTarget.attributes[3].value
                console.log(event.currentTarget)
                console.log(window.piece_id)
            $.ajax({
                url:  + game_id + "/make_move", // Route to the Script Controller method
                    type: "PUT",
                dataType: "json",
                    data: { 
                        piece_id: window.piece_id, 
                        x: x,
                        y: y,
                        }, // This goes to Controller in params hash, i.e. params[:file_name]
                 success: function(data, textStatus, jqHXR) {
                            // Do something with the response here
                            //editor.setValue(data.file_content) // Show the file contents in our editor.
                          },
                   error: function(jqXHR, status, err) {
                        alert("That was not a valid move!")
                        location.reload()
                         }
    });
        } );
    });
    
</script>
<h3 class='col-10 offset-5'><%= @game.name %></h3>
<h4 class='col-10 offset-5'>
  It's <%= @game.user_of_current_turn.email %>'s turn.
</h4>

<button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#myModal">Rage Quit!
</button>

<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="quitModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="quitModalLabel"><strong>Do you really want to quit?</strong> <br> **This will delete the whole game!!**</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/pVD53JffuTI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                </div>
      </div>
      <div class="modal-footer"> 
        <%= button_to "Rage Quit!", game_path(@game.id), :method => :delete, :class =>"btn btn-warning" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Nevermind.</button>
      </div>
    </div>
  </div>
</div>

<div class="castling-links">
        <%= link_to 'Castle Kingside', game_castle_kingside_path(:game_id => @game.id), method: :patch %>
        <%= link_to 'Castle Queenside', game_castle_queenside_path(:game_id => @game.id), method: :patch %>
</div>

<div class='col-10 offset-3'>
    <div class="chessboard">
        <table>
        <% 7.downto(0) do |y| %>
        <tr class="row">
            <% 0.upto(7) do |x| %>
                <% piece = @game.piece_at(x,y) %>           
                    <td class="droppable <%= black_white_cell(x,y) %>" data-x="<%= x %>" data-y="<%= y %>" data-game_id="<%= @game.id %>">
                <% if piece.id %>
                    <p class="draggable" data-id="<%= piece.id %>"><%= show_piece(piece)%></p>
                <% end %></td>
            <% end %>
        <% end %>         
    </div>
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fingerfehler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <%= link_to 'Chess', root_path, class: "navbar-brand" %>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link text-white' %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Sign in', new_user_session_path, class: 'nav-link text-white' %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link text-white' %></li>
          </ul>
        <% end %>
    </nav>
    <br class="clear-fix" />
    <!-- alerts for devise, should go under nav-bar -->
  <% if notice.present? %>           
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  

    <%= yield %>
  </body>
</html>